openapi: 3.0.3
info:
  title: 'SHARY - Regular'
  description: Регулярные выражения
  version: 2.0.0
paths: {}

components:
  schemas:
    FullRegularSchema:                                                      # - All Regular
      allOf:
        - $ref: '#/components/schemas/EmailRegularSchema'                   # Email
        - $ref: '#/components/schemas/InnRegularSchema'                     # INN
        - $ref: '#/components/schemas/PhoneNumberRegularSchema'             # Phone number
        - $ref: '#/components/schemas/PassportRegularSchema'                # Passport

      type: object

    PassportRegularSchema:                                                  # - Passport
      allOf:
        - $ref: '#/components/schemas/PassportNumberRegularSchema'          # Passport number
        - $ref: '#/components/schemas/PassportSeriesRegularSchema'          # Passport series

      type: object


    EmailRegularSchema:                                                     # Email
      type: object
      properties:
        email:
          type: string
          format: email
          pattern: '/^[A-Z0-9._%+-]+@[A-Z0-9-]+.+.[A-Z]{2,4}$/i'
          example: "user@example.com"

    InnRegularSchema:                                                       # INN
      type: object
      properties:
        inn:
          type: string
          pattern: '^(([0-9]{12})|([0-9]{10}))?$'
          example: "123453488322"

    PassportNumberRegularSchema:                                            # Passport number
      type: object
      properties:
        passportNumber:
          type: string
          pattern: '^([0-9]{6})?$'
          example: '454322'

    PassportSeriesRegularSchema:                                            # Passport series
      type: object
      properties:
        passportSeries:
          type: string
          pattern: '^([0-9]{2}\s{1}[0-9]{2})?$'
          example: '6282'

    PhoneNumberRegularSchema:                                               # Phone number
      type: object
      properties:
        phoneNumber:
          type: string
          minLength: 5
          maxLength: 15
          pattern: '^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$'
          example: "+79008883322"
